# For more information: https://laravel.com/docs/sail
version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
     - ./templates:/etc/nginx/templates
    ports:
     - "8876:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
